#!/bin/python3

import sys

if __name__ == "__main__":
    meal_cost = float(input().strip())
    tip_percent = int(input().strip())
    tax_percent = int(input().strip())
    tip_cost = meal_cost * tip_percent/100
    tax_cost = meal_cost * tax_percent/100
    total_cost = meal_cost + tip_cost + tax_cost
    total_cost = int(round(total_cost))
    print ("The total meal cost is " + str(total_cost) + " dollars.")
